[package]
name = "binance-async"
version = "0.10.5"
license = "MIT OR Apache-2.0"
authors = ["Flavio Oliveira <flavio@wisespace.io>"]
edition = "2018"

description = "Rust Library for the Binance API"
keywords = ["cryptocurrency", "trading", "binance"]
categories = ["api-bindings", "cryptography::cryptocurrencies"]
documentation = "https://docs.rs/crate/binance/"
repository = "https://github.com/wisespace-io/binance-rs"
readme = "README.md"

[badges]
travis-ci = { repository = "wisespace-io/binance-rs" }

[lib]
name = "binance"
path = "src/lib.rs"

[dependencies]
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
error-chain = { version = "0.12", default-features = false }
ring = "0.16"
reqwest = { version = "0.10", features = ["json"] }
url = "2.1"
async-tungstenite = { version = "0.5.0", features=["tokio-runtime", "async-tls"] }
tokio = { version = "0.2.21", features=["full"] }
async-tls = "0.7.0"
# tungstenite = "0.10"

[dev-dependencies]
csv = "1.0.0"
